### ISSUE TITLE
Where I need to calculate the similarity?

### ISSUE THREAD

**Issue by JiangWenqi** [oeg-upm/loom-ld#1]
Hi there, 

I want to know where I need to calculate the similarity?
1. after I got the whole result? and I compare those result from different data-sources?
2. or I parse sparql queries and compare the query conditions?

Could you please tell me what my initial step should be?

Best regards,

**Comment by AndreaCimminoArriaga** [comment]
Hello,

The similarity is computed by jena, and the metric is specified in the SPARQL query. For instance:
````
CONSTRUCT { 
  ?city1 owl:sameAs ?city2 .
} WHERE { 
    SERVICE <https://es.dbpedia.org/sparql> { 
       ?city1 foaf:name  ?fullName1 . 
       VALUES ?city1 { 
    		<http://dbpedia.org/resource/Madrid> 
                     <http://dbpedia.org/resource/Soria>
                     <http://es.dbpedia.org/resource/Sevilla> 
         }
   }
    SERVICE <https://es.dbpedia.org/sparql> {
        ?city2 foaf:name  ?fullName1 . 
          VALUES ?city2 {  
    		<http://dbpedia.org/resource/Madrid> 
                    <http://dbpedia.org/resoAZurce/Soria> 
          }
    }
    FILTER ( ?fullName1 = ?fullName2 )
}
````

In this case the similarity function is equals, and is specified by the ` FILTER ( ?fullName1 = ?fullName2 )`.

I think the best way to proceed is to have a code that can run the previous query. When that milestone is reached, then it will come the momento to extend the jena ARQ with new similarity functions.

Also as a side comment, I would suggest that this project is a maven dependency instead of a service. In this way, then we can pack the loom as different services (REST, MQTT, etc)

**Comment by JiangWenqi** [comment]
Hi Andrea,
Thank you for detailed replying.
I think I've done the demo query weeks ago, 
```java
Query query = QueryFactory.create(queryStr);
Model init = ModelFactory.createDefaultModel();
QueryExecution queryExecution = QueryExecutionFactory.create(query, init);
Model model = queryExecution.execConstruct();
model.write(System.out, "TURTLE");
```
and I've already parsed the query filter out.
```java
ElementGroup queryPattern = (ElementGroup) query.getQueryPattern();
for (Element element : queryPattern.getElements()) {
  if (element instanceof ElementFilter) {
    ElementFilter filter = (ElementFilter) element;
    System.out.println(filter.getExpr());
  }
}
```

So here is my next plan, I'll write two main modules,one is `core`, another is `web`,
I can build `core` to a maven dependency, and `web` as a service like you told me before.

What do you think?
Looking forward your reply.

Best regards,
Wenqi

**Comment by AndreaCimminoArriaga** [comment]
If you build the maven project I can upload it to maven central so it can be used as a maven dependency. Then, we can build a loom-service project that publishes the REST API if that is ok. But before publishing to the maven central I would like to see the core module with the tests to check how is used by a user.

**Comment by JiangWenqi** [comment]
So my next step is `Add new similarity functions to the ARQ`.
Thank you!
