### ISSUE TITLE
Custom ARQ Similarity Function

### ISSUE THREAD

**Issue by JiangWenqi** [oeg-upm/loom-ld#2]
Dear Andrea,

I wrote a demo of [CustomAggregateFunction](https://github.com/oeg-upm/loom-ld/blob/main/sparql_based-linking/src/main/java/loom/oeg/upm/examples/CustomAggregateFunction.java).

It is a aggregate function, I calculated the sum of prices in it.
Is this idea right? What will I do next?

Best regards,
Wenqi

**Comment by JiangWenqi** [comment]
Hi Andrea,

I wrote another simple [function](https://github.com/oeg-upm/loom-ld/blob/main/sparql_based-linking/src/main/java/loom/oeg/upm/examples/CustomSimilarityFunction.java)

But it doesn’t work, and I am on fixing it.
If you have some clues, please tell me.
Thank you

**Comment by AndreaCimminoArriaga** [comment]
HI @JiangWenqi, you are in the right path, that is exactly what you need to do. [Here you can find a list of string similarities implemented](https://github.com/AndreaCimminoArriaga/EvA4LD/tree/master/tdg.link_discovery.connector.sparql/tdg/link_discovery/connector/sparql/evaluator/arq/linker/string_similarities). The problem for you is the way the code is structured.

I think the best way to proceed is that you build an interface SparqlLinker (or similar) and then you build a class that implements such interface. Besides, you will need to create a package that will contain all the similarity functions needed. Finally, the class implementing the SparqlLinker will load such functions so when they are called in the sparql query jena is able to use them internally.

**Comment by JiangWenqi** [comment]
Thank you for sharing your code, Andrea, it helps a lot.
The demos I wrote is just for make sure if I am on right path.
Can you give me some small projects, articles or books for the structure you mentioned above.
I only have 3 experience in coding, and I want my code is elegant.

**Comment by AndreaCimminoArriaga** [comment]
Well, it is hard to give you projects for learning. Maybe the best way to proceed is for you to define a Java Interface with the functionalities that you think your code will offer, and the, we can discuss over it. After we have settle the interface, you can proceed with the implementation.

**Comment by JiangWenqi** [comment]
Dear @AndreaCimminoArriaga ,

I followed your [instructions](https://github.com/AndreaCimminoArriaga/EvA4LD/tree/master/tdg.link_discovery.connector.sparql/tdg/link_discovery/connector/sparql/evaluator/arq/linker/string_similarities) and developed some [code](https://github.com/oeg-upm/loom-ld/tree/main/sparql_based-linking/src/main/java/upm/oeg/loom/functions/similarities), I also studied  your project and am confused how to run or apply it, could you explain me more about it tomorrow? 

Best regards,
Wenqi

**Comment by AndreaCimminoArriaga** [comment]
I review the code, I saw you followed a similar structure as I did in the Eva4LD project; it's a good start. Now, before going further you [need to read](https://jena.apache.org/documentation/query/library-function.html) how to use custom functions in SPARQL queries that are ran using jena (who is going to load these functions from your classes). Once that part is clear:

1. Very likely you will need to refractor your code to get rid of the Eva4LD approach and create a custom one that works for your code.
2. Develop an interface for your Java class that will run the queries. (So anybody can view the methods that your class will implement)
3. Develop the Java interface that is able to run federated queries, and also, is capable of using the string metrics
4. You are done with the library ! :)

Check out the docs, we can talk about them this afternoon

**Comment by AndreaCimminoArriaga** [comment]
```sparql
SELECT ?name1 ?name2 ?score WHERE {
   SERVICE < > {
     ?subject1 rdfs:label ?name1 .
   }

  SERVICE <> {
    ?subject2  rdfs:label ?name2 .
  }
 BIND ( levenshtain(?name1, ?name2) AS ?score )
 FILTER (  ?score > 2 ) .
} ORDER BY ?score
```

**Comment by JiangWenqi** [comment]
Dear @AndreaCimminoArriaga ,

I restructured the project followed your suggestions, and write a [example](https://github.com/oeg-upm/loom-ld/blob/main/sparql_based-linking/src/main/java/upm/oeg/loom/examples/CustomFunctionExample.java). 
However I am not familiar with sqarql, I am not sure whether my functions work, can you give me a more specific sparql, so I can run it and debug it.

Best regards,
Wenqi

**Comment by AndreaCimminoArriaga** [comment]
https://jena.apache.org/documentation/query/writing_functions.html

**Comment by JiangWenqi** [comment]
Dear @AndreaCimminoArriaga,

I found the reason that I was unable to produce the similarity grades, because I use `nodevalue.toString()` instead of `nodevalue.asString(),`  and you can check this [example](https://github.com/oeg-upm/loom-ld/blob/main/sparql_based-linking/src/main/java/upm/oeg/loom/examples/CustomFunctionExample.java).
If you think it is OK, we can close this issue, and move to next step.

Thank you!
Best regards,

Wenqi

**Comment by AndreaCimminoArriaga** [comment]
Great! yes it now it works we can close this issue
