### ISSUE TITLE
Next step for LOOM

### ISSUE THREAD

**Issue by JiangWenqi** [oeg-upm/loom-ld#3]
Dear @AndreaCimminoArriaga ,

What is the next step...

Best regards,

Wenqi

**Comment by AndreaCimminoArriaga** [comment]
Dear @JiangWenqi, I think these can be our following steps:
 * Demo linking two datasets with 2 queries one using levenshtein and another the cosine similarity. The output of the query shall be stored in a file. The output must be in RDF using NT serialisation, and the links among the resources must be owl:sameAs.
 * Adapt one linking scenario from the [OAEI](http://oaei.ontologymatching.org/) and test it with the tool. The results of the OAEI should include the results achieved by other tools, try to compare with them.

For the moment I think this would be all, let me know if you have any questions.
