### ISSUE TITLE
Run Queries and Test Performance

### ISSUE THREAD

**Issue by JiangWenqi** [oeg-upm/loom-ld#4]
Dear @JiangWenqi, I think these can be our following steps:

1. Demo linking two datasets with 2 queries one using levenshtein and another the cosine similarity. The output of the query shall be stored in a file. The output must be in RDF using NT serialisation, and the links among the resources must be owl:sameAs.
2. Adapt one linking scenario from the [OAEI](http://oaei.ontologymatching.org/) and test it with the tool. The results of the OAEI should include the results achieved by other tools, try to compare with them.

For the moment I think this would be all, let me know if you have any questions.

**Comment by AndreaCimminoArriaga** [comment]
Sparql to test with https://datos.bne.es/sparql

**Comment by JiangWenqi** [comment]
Test this [dataset](https://hobbit-project.github.io/OAEI_2021.html)

**Comment by JiangWenqi** [comment]
for organising a bit the meeting I would suggest that you prepare a few slides explaining the two next steps that we agreed on last week and your progress.

- For the demo, the slides should contain the SPARQL endpoints chosen for the linking tasks. Then, they should explain the resources chosen to be linked, their attributes, and the metrics. For instance, the resources are foaf:Person and sch:Person, their attributes to be linked are foaf:name and sch:firstName, such:lastName. Finally, it would be great to see the SPARQL query in the slides and, then, run the query to see the results on the software.

- Regarding the OAEI, the slides should present a summary of your findings of the contest. Also, if you picked already a dataset explain your choice and explain a bit the scenario of the dataset. Finally, if for adopting the OAEI you had to modify your code provide a slide explaining the changes shortly.

**Comment by JiangWenqi** [comment]
- Prepare slides summarizing the work of this week
- Download the chosen OAEI datasets (SPIMBENCH and Spatial data)
- Link locally the dataset SPIMBENCH
    - Show in the slides how this data looks like (number of instances, attributes, etc.)
    - Show in the slides the query used for the linking
- Link locally the dataset Spatial data
    - Show in the slides how this data looks like (number of instances, attributes, etc.)
    - Show in the slides the query used for the linking

**Comment by JiangWenqi** [comment]
- Run the queries in challenge 1 datasets (the small and large ones)
- Store the results in files
- Compare the results with the gold standard (GS)
    - Calculate how many links there are in common between your results and the Gold standard
    - How many exist in the GS that do not exist in your results
    - How many exist in your results that do not in the GS
- Do the same for Geo

**Comment by JiangWenqi** [comment]
1. Run linking in small and large datasets from SPIMBENCH and compare results with gold standard
2. Fix SPARQL for linking DE-9IM and see the results with the gold standard
3. Given the results file R and the gold standard file G:
    - How many links in R exists in G (intersection): tp
    - How many links in R exists that do not in G (R - G): fp
    - How many links in exists in R that do not in R: fn
    - How many link exists in G that do not in R: fn
4. Calculate these metrics after the executions of linking queries
